apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: z1s40cdmw-go
  janus-idp.io/tekton: z1s40cdmw-go
  backstage.io/kubernetes-id: z1s40cdmw-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: z1s40cdmw-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
